flags: {}
packages:
- '.'
- subhask/
extra-deps:
    [ gamma-0.9.0.2
    , continued-fractions-0.9.1.1
    , converge-0.1.0.1
    , MonadRandom-0.4
    , bytes-0.15.0.1 
    , cassava-0.4.3.1
    , hmatrix-0.16.1.5
    , hyperloglog-0.3.4
    , lens-4.12.3
    , parallel-3.2.0.6
    , semigroups-0.16.2.2
    , vector-0.10.12.3
    , cereal-0.4.1.1
    , reflection-2
    , safecopy-0.8.6
    , approximate-0.2.2.1
    , primitive-0.6.1.0
    ]
resolver: lts-5.14
